letter = "А" | "Б" | "В" | "Г" | "Д" | "Е" | "Ё" 
                     | "Ж" | "З" | "И" | "І" | "Й" | "К" | "Л"
                     | "М" | "Н" | "О" | "П" | "Р" | "С" | "Т"
                     | "У" | "Ф" | "Х" | "Ц" | "Ч" | "Ш" | "Щ"
                     | "Ъ" | "Ы" | "Ь" | "Э" | "Ю" | "Я" | "Ѣ"
                     | "Ѳ" | "Ѵ" | "Ѥ" | "Ѧ" | "Ѫ" | "Ѩ" | "Ѭ" ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

all_char = letter | digit | punct

string = '"' , { all_char - '"' }, '"' ;
